### ISSUE TITLE
Error: Unable to access jarfile jTessBoxEditor.jar

### ISSUE THREAD

**Issue by PedroBarcha** [nguyenq/jTessBoxEditor#5]
Hi there. So, I've just tried to use JTess, but when I run:
`java -Xms128m -Xmx1024m -jar jTessBoxEditor`
All i I get is:
`Error: Unable to access jarfile jTessBoxEditor.jar`

I noticed that in readme.html is written that jdk8+ is required, while github's readme says jdk7+. My current version is 7.3, could that be the problem?

**Comment by nguyenq** [comment]
The command should be:

`java -Xms128m -Xmx1024m -jar jTessBoxEditor.jar`

Or launch the program using the `train` script file.

**Comment by PedroBarcha** [comment]
uhn... I guess that I dind't build it properly. Could you tell me how to do that?

**Comment by nguyenq** [comment]
It's Ant-based. So execute: `ant jar`

**Comment by PedroBarcha** [comment]
Ok, I could run the software properly, using an older version of it. However, with the current github's version, when I run:
`java -Xms128m -Xmx1024m -jar jTessBoxEditor.jar`
I get:
`Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: net/sourceforge/tess4j/ITesseract`
Checking net/sourceforge, I realized that there's no tess4j directory there. Is that how it's supposed to be?

**Comment by nguyenq** [comment]
Get the latest version from master branch; make sure you have `tess4j-3.2.2-SNAPSHOT.jar`, which is under `lib` folder.

**Comment by PedroBarcha** [comment]
Still having the same problem, am I supposed to do something with `tess4j-3.2.2-SNAPSHOT` ?
Still getting:
```
java -Xms128m -Xmx1024m -jar jTessBoxEditor.jar

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: net/sourceforge/tess4j/ITesseract
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6218)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6207)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6207)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6207)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6207)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6207)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6207)
	at java.awt.Component.isCoalesceEventsOverriden(Component.java:6207)
	at java.awt.Component.access$500(Component.java:186)
	at java.awt.Component$3.run(Component.java:6172)
	at java.awt.Component$3.run(Component.java:6170)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Component.checkCoalescing(Component.java:6169)
	at java.awt.Component.<init>(Component.java:6138)
	at java.awt.Container.<init>(Container.java:283)
	at java.awt.Window.<init>(Window.java:535)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at net.sourceforge.tessboxeditor.Gui.<init>(Unknown Source)
	at net.sourceforge.tessboxeditor.GuiWithMRU.<init>(Unknown Source)
	at net.sourceforge.tessboxeditor.GuiWithEdit.<init>(Unknown Source)
	at net.sourceforge.tessboxeditor.GuiWithSpinner.<init>(Unknown Source)
	at net.sourceforge.tessboxeditor.GuiWithFont.<init>(Unknown Source)
	at net.sourceforge.tessboxeditor.GuiWithLaF.<init>(Unknown Source)
	at net.sourceforge.tessboxeditor.GuiWithTools.<init>(Unknown Source)
	at net.sourceforge.tessboxeditor.GuiWithGenerator.<init>(Unknown Source)
	at net.sourceforge.tessboxeditor.GuiWithTrainer.<init>(Unknown Source)
	at net.sourceforge.tessboxeditor.GuiWithValidator.<init>(Unknown Source)
	at net.sourceforge.tessboxeditor.GuiWithValidator$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.tess4j.ITesseract
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more

```

**Comment by nguyenq** [comment]
The project has just been updated with latest dependencies. Please get the latest source from github and try again. Thanks.

**Comment by PedroBarcha** [comment]
I'm with the latest branch now, however it's still yielding the exactly same error. 
Why can't java find the `ITesseract` class?

**Comment by nguyenq** [comment]
`ITesseract` is from `tess4j.jar`. You need to make sure you have all the required JARs and they are in the program's classpath at compile and runtime.

A pre-built binary is provided at https://sourceforge.net/projects/vietocr/files/jTessBoxEditor/.

**Comment by PedroBarcha** [comment]
Just got the latest version here and it's still yielding the same error.
Everything worked fine with the pre-compiled version, though. I'm using it for a few day now. Thanks!

**Comment by nguyenq** [comment]
I suspect one of your JARs is corrupted. You may want to wipe it clean and start with a fresh copy.

**Comment by PedroBarcha** [comment]
Unfortunately, that's exactly what I've done. Have you tried it as well?

**Comment by nguyenq** [comment]
I had no issues. I was unable to reproduce your problem.

**Comment by PedroBarcha** [comment]
Seems like I've got it now! 
I was compiling the program with `ant jar` , as you told me to do, however it's necessary to use an `ant compile` before it. I'd never used ant before, I'm sorry.
Thanks a lot for the attention!

**Comment by nguyenq** [comment]
Glad that you finally were able to resolve it.
